name: PixplazePlayerSuspect
version: '${project.version}'
main: com.pixplaze.plugin.PixplazePlayerSuspect
api-version: 1.18
authors: [ Emberati ]

commands:
  suspect:
    description: To suspect player
    usage: /suspect <username>

  desuspect:
    description: To desuspect player
    usage: /desuspect <username>